PROBLEM: Find the Difference
Statement:
      You are given two strings s and t.
     String t is generated by random shuffling string s and then add one more letter at a random position.
     Return the letter that was added to t.
Example:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

Solution:
 class FindTheDifference{
    public char findTheDifference(String s, String t) {
       char result=0;
       for(char ch:s.toCharArray()){
        result^=ch;
       }
       for(char ch2:t.toCharArray()){
        result^=ch2;
       }
       return result;
    }
}
